### ISSUE TITLE
The type initializer for 'VitaNex.Text.UOFont' threw an exception.

### ISSUE THREAD

**Issue by miguelmoraleda** [Vita-Nex/Core#3]
Im getting this error when trying 5.1. Is this something my version of mono don't support?. Im running mono 5.12

Log
https://pastebin.com/ZsVQv2Hb

**Comment by qbradq** [comment]
This is a problem with Mono. They do not support some assemblies, and in this case do not support a particular class or namespace. Although if VNC is intended to support Mono then it would be a bug.
