### ISSUE TITLE
Core and cellar module dont compile on newest servuo

### ISSUE THREAD

**Issue by Scrubtasticx** [Vita-Nex/Core#4]
Whenever you get time ;)  thanks.

**Comment by OrbitStorm** [comment]
ServUO recently stripped CustomsFramework from the repo, likely resulting in your issue.

**[Per Vorspire](https://www.servuo.com/threads/savedata-and-readdata-problem.12571/#post-75772)**:

> You can safely remove the code that's causing issues. Vita-Nex does not use any of the CustomsFramework, it just had to override certain serialization methods for the implementation at the time.
